
name: Build Angular and publish package

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: | 
 	  cd angular-web
 	  npm ci
      - name: Build Angular
        run: npm run build -- --configuration production

      - name: Prepare artifact package
        run: |
          mkdir package
          cp -r dist/* package/
          cp package.json package/
          cd package
          npm pkg set name="@${{ github.repository_owner }}/angular-web"
          npm pkg set version="1.0.${{ github.run_number }}"
          npm pkg set publishConfig.registry="https://npm.pkg.github.com"

      - name: Publish to GitHub Packages
        run: npm publish ./package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}